// ****************************************************************************
// CUI
//
// The Advanced Framework for Simulation, Integration, and Modeling (AFSIM)
//
// The use, dissemination or disclosure of data in this file is subject to
// limitation or restriction. See accompanying README and LICENSE for details.
// ****************************************************************************
// Extension configuration file.
//
// This file provides a mechanism to register the standard extensions and any optional extensions that
// are included in the build package. It is typically included by the main file of an application.
//
// This file contains two main methods:
//
// -) RegisterBuiltinExtensions. This will register the standard extensions that are included with WSF:
//       air_traffic
//       console_output
//       csv_event_output
//       dis_interface
//       event_output
//       event_pipe
//       ext_interface
//       grammar_interface
//       osm_traffic
//       profiling
//       road_traffic
//       sea_traffic
//       wsf_draw
//
// -) RegisterOptionalExtensions. This will register any and all optional extensions that are included
//    in the build package.
//
// To use this file, the main application does something like:
//
//    #include "wsf_extensions.hpp"
//      ...
//    int main(int argc, char* argv[])
//    {
//       WsfApplication app;
//       RegisterBuiltinExtensions(app);
//       RegisterOptionalExtensions(app);
//       ...
//    }
//
// An application can request that specific extensions be excluded because they are needed by the
// application. In this case preprocessor directives may be defined BEFORE including this file which
// will indicate that specific extensions should be excluded.
//
//    #define WSF_EXCLUDE_EXTENSION_<name>
//    ... repeat as necessary ...
//    #include "wsf_extensions.hpp"
//
// For example, to exclude all of the 'traffic' extensions:
//
//    #define WSF_EXCLUDE_EXTENSION_air_traffic
//    #define WSF_EXCLUDE_EXTENSION_road_traffic
//    #define WSF_EXCLUDE_EXTENSION_sea_traffic
//    #include "wsf_extensions.hpp"
//
// There is no harm in excluding an extension that in not included in the build package.

#include "UtLog.hpp"

#include "WsfApplication.hpp"

static void PrintOptionalExtensionIncluded(const std::string& aName, ut::log::MessageStream& aStream)
{
   static bool firstEntry = true;
   if (!firstEntry)
   {
      aStream << ", ";
   }
   firstEntry = false;
   aStream << aName;
}

//! Register optional extensions
//! @param aApplication The application object.
inline void RegisterOptionalExtensions(WsfApplication& aApplication)
{
   auto out = ut::log::info() << "Extensions Included: ";
   auto listNote = out.AddNote();
   
   // WARNING: This code is generated by CMake.  Do not hand-edit.

#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_sensor_plot_lib)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_sensor_plot_lib)))
   // PrintOptionalExtensionIncluded("sensor_plot_lib", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, sensor_plot_lib);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_cyber)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_cyber)))
   // PrintOptionalExtensionIncluded("wsf_cyber", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_cyber);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_grammar_check)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_grammar_check)))
   // PrintOptionalExtensionIncluded("wsf_grammar_check", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_grammar_check);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_l16)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_l16)))
   // PrintOptionalExtensionIncluded("wsf_l16", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_l16);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_mil)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_mil)))
   PrintOptionalExtensionIncluded("wsf_mil", listNote);
   WSF_REGISTER_EXTENSION(aApplication, wsf_mil);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_mil_parser)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_mil_parser)))
   // PrintOptionalExtensionIncluded("wsf_mil_parser", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_mil_parser);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_mtt)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_mtt)))
   // PrintOptionalExtensionIncluded("wsf_mtt", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_mtt);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_nx)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_nx)))
   // PrintOptionalExtensionIncluded("wsf_nx", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_nx);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_parser)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_parser)))
   // PrintOptionalExtensionIncluded("wsf_parser", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_parser);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_ripr)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_ripr)))
   // PrintOptionalExtensionIncluded("wsf_ripr", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_ripr);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_space)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_space)))
   // PrintOptionalExtensionIncluded("wsf_space", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_space);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_weapon_server)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_weapon_server)))
   // PrintOptionalExtensionIncluded("wsf_weapon_server", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_weapon_server);
#endif
#if ((!defined(WSF_INCLUDE_EXTENSIONS) && !defined(WSF_EXCLUDE_EXTENSION_wsf_simdis)) || \
     ( defined(WSF_INCLUDE_EXTENSIONS) &&  defined(WSF_INCLUDE_EXTENSION_wsf_simdis)))
   // PrintOptionalExtensionIncluded("wsf_simdis", listNote);
   // WSF_REGISTER_EXTENSION(aApplication, wsf_simdis);
#endif
}

//! Register extensions that are built-in to WSF.
//! An application which wishes to use all available extensions can call this method.
//! @param aApplication The application object.
inline void RegisterBuiltinExtensions(WsfApplication& aApplication)
{
#if !defined(WSF_EXCLUDE_EXTENSION_air_traffic)
   WSF_REGISTER_EXTENSION(aApplication, air_traffic);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_console_output)
   WSF_REGISTER_EXTENSION(aApplication, console_output);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_csv_event_output)
   WSF_REGISTER_EXTENSION(aApplication, csv_event_output);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_dis_interfacee)
   WSF_REGISTER_EXTENSION(aApplication, dis_interface);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_event_output)
   WSF_REGISTER_EXTENSION(aApplication, event_output);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_event_pipe)
   WSF_REGISTER_EXTENSION(aApplication, event_pipe);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_ext_interface)
   WSF_REGISTER_EXTENSION(aApplication, ext_interface);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_grammar_interface)
   WSF_REGISTER_EXTENSION(aApplication, grammar_interface);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_osm_traffic)
   WSF_REGISTER_EXTENSION(aApplication, osm_traffic);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_profiling)
   WSF_REGISTER_EXTENSION(aApplication, profiling);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_road_traffic)
   WSF_REGISTER_EXTENSION(aApplication, road_traffic);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_sea_traffic)
   WSF_REGISTER_EXTENSION(aApplication, sea_traffic);
#endif
#if !defined(WSF_EXCLUDE_EXTENSION_wsf_draw)
   WSF_REGISTER_EXTENSION(aApplication, wsf_draw);
#endif
}
